const events = [
  {
    id: 1,
    title: "GDGC Hackathon 2026",
    date: "2026-01-15",
    time: "09:00",
    venue: "Central Auditorium",
    district: "Central Hall",
    description: "Join our 48-hour coding challenge where students from all disciplines can collaborate and create innovative solutions. Learn from industry experts and compete for amazing prizes!",
    expectations: "This is a high-energy event perfect for coders and innovators. Bring your laptops, ideas, and enthusiasm. Food and refreshments will be provided throughout.",
    category: "tech",
    capacity: 150,
    organizer: "Google Developer Group",
    contact: "gdg@campus.edu",
    duration: 48,
    tags: ["hackathon", "coding", "innovation", "prizes"],
    attendees: 120
  },
  {
    id: 2,
    title: "AI & Machine Learning Workshop",
    date: "2026-01-12",
    time: "14:00",
    venue: "Tech Lab 3",
    district: "East Campus",
    description: "Explore the fascinating world of AI and Machine Learning. Hands-on session with Python, TensorFlow, and real-world datasets. Perfect for beginners and intermediate learners.",
    expectations: "Bring your laptops. Basic Python knowledge recommended. We'll cover supervised learning, neural networks, and practical implementation with live coding examples.",
    category: "tech",
    capacity: 80,
    organizer: "CS Department",
    contact: "cs.dept@campus.edu",
    duration: 3,
    tags: ["AI", "machine-learning", "python", "workshop"],
    attendees: 65
  },
  {
    id: 3,
    title: "Annual Sports Championship",
    date: "2026-01-20",
    time: "10:00",
    venue: "Sports Complex",
    district: "Sports Complex",
    description: "Watch the most exciting inter-college sports championship. Multiple events including basketball, cricket, badminton, and tennis. Cheer for your favorite teams!",
    expectations: "Get ready for some thrilling matches. Food stalls available. Bring your enthusiasm and support your college team. Free entry for all students.",
    category: "sports",
    capacity: 500,
    organizer: "Sports Committee",
    contact: "sports@campus.edu",
    duration: 8,
    tags: ["sports", "championship", "cricket", "basketball"],
    attendees: 450
  },
  {
    id: 4,
    title: "Cultural Fest 2026",
    date: "2026-01-25",
    time: "17:00",
    venue: "Open Air Theatre",
    district: "North Campus",
    description: "Celebrate the rich diversity of our campus! Performances include classical dance, music, theatre, and comedy. Food from different cultures. A night of colors, music, and joy!",
    expectations: "Experience diverse cultural performances. Multiple food stalls with cuisines from around the world. Participate in fun activities and win prizes. Dress up in traditional attire!",
    category: "cultural",
    capacity: 1000,
    organizer: "Cultural Committee",
    contact: "culture@campus.edu",
    duration: 5,
    tags: ["culture", "fest", "music", "performance"],
    attendees: 850
  },
  {
    id: 5,
    title: "Entrepreneurship Summit",
    date: "2026-01-18",
    time: "09:00",
    venue: "Business Complex",
    district: "South Campus",
    description: "Learn from successful entrepreneurs and business leaders. Keynote speeches, panel discussions, and networking opportunities. Perfect for aspiring startups!",
    expectations: "Interactive sessions with industry experts. Learn about fundraising, business strategy, and scaling. Networking lunch included. Business cards recommended!",
    category: "academic",
    capacity: 200,
    organizer: "Entrepreneurship Cell",
    contact: "startup@campus.edu",
    duration: 6,
    tags: ["startup", "business", "entrepreneurship", "networking"],
    attendees: 180
  },
  {
    id: 6,
    title: "Photography Exhibition",
    date: "2026-01-22",
    time: "11:00",
    venue: "Art Gallery",
    district: "West Campus",
    description: "Showcase of stunning photographs by student photographers. Exhibits include landscapes, portraits, street photography, and experimental digital art.",
    expectations: "Get inspired by beautiful visual stories. Participate in a photography workshop. Vote for your favorite photos. Meet the photographers and share your feedback.",
    category: "cultural",
    capacity: 300,
    organizer: "Photography Club",
    contact: "photoclub@campus.edu",
    duration: 4,
    tags: ["photography", "art", "exhibition", "visual"],
    attendees: 250
  },
  {
    id: 7,
    title: "Web Development Bootcamp",
    date: "2026-01-28",
    time: "13:00",
    venue: "Computer Lab 1",
    district: "East Campus",
    description: "Intensive 5-day bootcamp covering HTML, CSS, JavaScript, React, and backend technologies. Learn modern web development from scratch to deployment.",
    expectations: "Daily coding sessions, project-based learning, mentor support. You'll build a complete project by the end. Certificate provided upon completion.",
    category: "tech",
    capacity: 40,
    organizer: "Tech Club",
    contact: "techclub@campus.edu",
    duration: 40,
    tags: ["web-development", "coding", "bootcamp", "javascript"],
    attendees: 38
  },
  {
    id: 8,
    title: "Career Fair 2026",
    date: "2026-02-01",
    time: "10:00",
    venue: "Central Hall",
    district: "Central Hall",
    description: "Meet top recruiters from leading companies. Explore job opportunities, internships, and career paths. Resume review sessions available.",
    expectations: "Dress professionally. Bring multiple copies of your resume. Speak with recruiters about opportunities. Participate in company presentations and Q&A sessions.",
    category: "academic",
    capacity: 800,
    organizer: "Placement Cell",
    contact: "placement@campus.edu",
    duration: 6,
    tags: ["career", "jobs", "recruitment", "internship"],
    attendees: 700
  },
  {
    id: 9,
    title: "Debate Competition",
    date: "2026-01-30",
    time: "14:00",
    venue: "Seminar Hall",
    district: "North Campus",
    description: "Inter-house debate competition on relevant social and political topics. Showcase your speaking and critical thinking skills on the big stage!",
    expectations: "Engaging debates on current affairs. Audience participation encouraged. Winners announced with attractive prizes. All welcome to participate or attend.",
    category: "social",
    capacity: 150,
    organizer: "Debate Society",
    contact: "debate@campus.edu",
    duration: 3,
    tags: ["debate", "speaking", "competition", "critical-thinking"],
    attendees: 120
  },
  {
    id: 10,
    title: "Movie Night - Cinema Under Stars",
    date: "2026-01-29",
    time: "19:00",
    venue: "Amphitheater",
    district: "South Campus",
    description: "Relax and enjoy a movie under the stars! Multiple screenings throughout the night with different genres. Popcorn and refreshments available.",
    expectations: "Bring your blankets and friends. Free screenings. Comfortable seating arrangement. Popular Bollywood and Hollywood movies will be screened.",
    category: "social",
    capacity: 400,
    organizer: "Student Council",
    contact: "council@campus.edu",
    duration: 3,
    tags: ["movie", "entertainment", "social", "fun"],
    attendees: 350
  },
  {
    id: 11,
    title: "Fitness & Wellness Seminar",
    date: "2026-02-05",
    time: "08:00",
    venue: "Sports Ground",
    district: "Sports Complex",
    description: "Learn about physical fitness, mental health, and overall wellness. Yoga sessions, nutrition workshops, and fitness coaching by certified trainers.",
    expectations: "Morning yoga, strength training sessions, nutrition talks. Bring yoga mats. Sessions for beginners and advanced. Free health screening available.",
    category: "social",
    capacity: 200,
    organizer: "Fitness Club",
    contact: "fitness@campus.edu",
    duration: 4,
    tags: ["fitness", "wellness", "yoga", "health"],
    attendees: 165
  },
  {
    id: 12,
    title: "Creative Writing Workshop",
    date: "2026-02-03",
    time: "15:00",
    venue: "Literature Room",
    district: "West Campus",
    description: "Develop your creative writing skills with experienced mentors. Write poetry, short stories, and essays. Share your work and get constructive feedback.",
    expectations: "Interactive writing sessions, reading circles, feedback from peers. Bring your ideas and notebooks. No experience necessary. Open mic session included.",
    category: "cultural",
    capacity: 60,
    organizer: "Literary Club",
    contact: "literaryclub@campus.edu",
    duration: 2,
    tags: ["writing", "creative", "literature", "workshop"],
    attendees: 50
  }
];

// Save to localStorage on first load
if (!localStorage.getItem("events")) {
  localStorage.setItem("events", JSON.stringify(events));
}
